# Generated by Django 5.0.3 on 2024-03-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cartitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
