# Generated by Django 4.2.6 on 2024-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cartitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
