# Generated by Django 4.2.6 on 2024-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_name', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=128)),
                ('tags', models.CharField(max_length=128)),
            ],
        ),
    ]
